### ISSUE TITLE
iOS build error.

### ISSUE THREAD

**Issue by safanmomin** [InteractiveObject/StarIOPlugin#9]
I'm working on iPad with iOS verion 8.1.1. I'm trying to implement the plugin with a simple example but everytime I try to build the app it fails. Upon summing out the log it returns the following error:

Error: [xcode-build] Compile /tmp/builds/3gOpJ8aVCHug1UbvdW/app/Plugins/StarIOPlugin-master/src/ios/StarIOPlugin.m: In file included from /tmp/builds/3gOpJ8aVCHug1UbvdW/app/Plugins/StarIOPlugin-master/src/ios/StarIOPlugin.m:30:
/tmp/builds/3gOpJ8aVCHug1UbvdW/app/Plugins/StarIOPlugin-master/src/ios/StarIOPlugin.h:39:9: fatal error: 'StarIO/SMPort.h' file not found

I don't know much about objective-c but it has something to do with the file which is being imported in StarIOPlugin.h line 39.

**Comment by younes200** [comment]
Please use the last lib of StarIO from their website, should fix this issue

**Comment by mgatto** [comment]
Hi, I also get an error:

` ...Plugins/fr.sellsy.startio/StarIOPlugin.h:39:9: fatal error: `
`      'StarIO/SMPort.h' file not found`
` #import <StarIO/SMPort.h>`

I've followed all the instructions for adding StarIO.framework to the build phases and such. How do I make it find the required header?

**Comment by RileyDavidson-Evans** [comment]
@mgatto I'm experiencing the same issue, have you had any luck resolving this?

**Comment by jyoti007** [comment]
@safanmomin I am also facing same Issue any luck. @RileyDavidson-Evans Please help me out

**Comment by envisiondata** [comment]
I did not. You can look at the people that cloned this repo and see if they fixed it. 

James
